In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [28]:
df = pd.read_csv(r"C:\Users\Srushti\OneDrive\Desktop\creditcard.csv")

In [29]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [30]:
#Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [31]:
#checking for null value
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [32]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.759061e-12,-8.251130e-13,-9.654937e-13,8.321385e-13,1.649999e-13,4.248366e-13,-3.054600e-13,8.777971e-14,-1.179749e-12,...,-3.405756e-13,-5.723197e-13,-9.725856e-13,1.464150e-12,-6.987102e-13,-5.617874e-13,3.332082e-12,-3.518874e-12,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [33]:
#Count of legit transactions & fake transactions
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [34]:
# 0->Normal Transaction
# 1->Fraudelent Transaction
#Imbalanced Data

In [35]:
authentic=df[df.Class==0]
fake=df[df.Class==1]

In [36]:
print(authentic.shape)
print(fake.shape)

(284315, 31)
(492, 31)

In [37]:
authentics=authentic.sample(n=492)

In [38]:
print(authentics.shape)

(492, 31)

In [39]:
new_df = pd.concat([authentics,fake],axis=0)

In [40]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
224728,143934.0,1.498394,-0.949192,-3.053452,0.386249,0.711932,-1.160228,1.434537,-0.686675,-0.182338,...,0.448120,0.649553,-0.488158,0.615833,0.555124,0.962391,-0.217546,-0.031000,360.00,0
121248,76124.0,1.048950,0.036934,0.472779,1.355336,-0.259927,0.021148,-0.017564,0.132825,0.076499,...,-0.023132,0.045010,-0.071353,0.222434,0.580501,-0.344114,0.028040,0.012147,38.44,0
92465,63942.0,1.238030,-0.083892,0.043837,0.470286,0.016496,0.270433,-0.152622,0.102227,0.342491,...,-0.251243,-0.628245,-0.154345,-0.815907,0.559773,0.323808,-0.033412,-0.007062,23.82,0
81780,59084.0,-0.321069,-0.016491,1.165451,-3.177073,-0.007103,-0.833038,0.762388,-0.218434,1.758308,...,0.068058,0.642829,-0.354417,0.034634,0.114207,-0.943875,0.022203,-0.085472,14.00,0
66993,52319.0,0.935705,-1.977958,-0.070570,-1.482595,-1.288353,0.213210,-0.701024,-0.109696,-2.149585,...,-0.188864,-0.873302,-0.269691,-0.845093,0.184743,-0.392619,-0.013220,0.065178,327.20,0

In [41]:
#Dataset Is Balanced Now
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [42]:
#Splitting the data into input values(Features) and targets
X=new_df.drop(columns='Class',axis=1)
Y=new_df['Class']

In [43]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
224728  143934.0  1.498394 -0.949192 -3.053452  0.386249  0.711932 -1.160228
121248   76124.0  1.048950  0.036934  0.472779  1.355336 -0.259927  0.021148
92465    63942.0  1.238030 -0.083892  0.043837  0.470286  0.016496  0.270433
81780    59084.0 -0.321069 -0.016491  1.165451 -3.177073 -0.007103 -0.833038
66993    52319.0  0.935705 -1.977958 -0.070570 -1.482595 -1.288353  0.213210
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
224728  1.434537 -0.686675 -0.182338  ...  0.537557  0.448120  0.649553
121248 -0.017564  0.132825  0.076499  ... -0.151642 -0.023132  0.045010
92465  -0.152622  0.102227  0.342491  ... -0.062295 -0.251243 -0.628245
81780   0.762388 -0.218434  1.758308  ... -0.086751  0.068058  0.642829
66993  -0.701024 -0.109696 -2.149585  ...  0.446082 -0.188864 -0.873302
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
224728 -0.488158  0.615833  0.555124  0.962391 -0.217546 -0.031000  360.00
121248 -0.071353  0.222434  0.580501 -0.344114  0.028040  0.012147   38.44
92465  -0.154345 -0.815907  0.559773  0.323808 -0.033412 -0.007062   23.82
81780  -0.354417  0.034634  0.114207 -0.943875  0.022203 -0.085472   14.00
66993  -0.269691 -0.845093  0.184743 -0.392619 -0.013220  0.065178  327.20
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [44]:
print(Y)

224728    0
121248    0
92465     0
81780     0
66993     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [45]:
#Splitting the data into training data and testing data
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [46]:
print(X.shape,X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)

In [50]:
#Model Training, Logistic Regression
model = LogisticRegression()

In [51]:
#Training the model with the training data
model.fit(X_train,Y_train)

LogisticRegression()

In [52]:
#Model evaluation

In [55]:
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [56]:
print("Accuracy on training data : " , training_data_accuracy)

Accuracy on training data :  0.940279542566709

In [57]:
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

In [58]:
print("Accuracy on training data : " , test_data_accuracy)

Accuracy on training data :  0.9137055837563451